---
entrada:
  db:
    host: 'labs-db1.sidnlabs.nl'
    name: 'entrada2'
    user: 'entrada2'
    password: 'Soz25jdvW6PuPGps'
  parquet:
   file:
     max-size: 256
  worker:
    sleep: 10
    stalled: 15
  schedule:
    updater: 60
    iceberg-comitter: 1
  security:
    token:
      admin: '94591089610224297274859827590711'
  privacy:
    enabled: false
  directory:
    pcap: 'pcap'
    reference: 'reference'
  s3:
    bucket: 'maarten-dev'
    access-key: 'FnrCQc3JQXEM1OwAtrSg'
    secret-key: 'dNITppQxnZbjIHs1AOejZuPDnNOG5emYHhbj5ar2'
    region: 'eu-west-1'
    endpoint: 'https://s3-lb.sidnlabs.nl:9000'
  metrics:
    enabled: true
    graphite:
      host: entrada-mon.sidnlabs.nl
      port: 2003
      protocol: 'Plaintext'
      step: 60 # secs
      tags-as-prefix: 'prefix'
      prefix: 'entrada2-test'  
    
spring:
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: '2GB'
      max-request-size: '2GB'

  datasource:
    url: 'jdbc:postgresql://${entrada.db.host}:5432/${entrada.db.name}'
    username: ${entrada.db.user}
    password: ${entrada.db.password}

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: 'org.hibernate.dialect.PostgreSQLDialect'

  cloud:
    bootstrap:
      enabled: true
    kubernetes:
      config:
        enabled: true
      enabled: true
      reload:
        enabled: true
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
          workerClient:
            url: 'http://entrada2-controller-service.entrada.svc.cluster.local:8091/api/v1'
            defaultRequestHeaders:
              'X-API-KEY': '${entrada.security.token.admin}'
            dismiss404: true
          maxmindClient:
            url: 'https://download.maxmind.com/app/geoip_download?suffix=tar.gz'
            dismiss404: false


iceberg:
  catalog:
    url: 'https://iceberg-catalog.sidnlabs.nl'
    token: 'secret-123'
  bucket: '${entrada.s3.bucket}'
  warehouse-dir: 'warehouse'
  endpoint: '${entrada.s3.endpoint}'
  access-key: '${entrada.s3.access-key}'
  secret-key: '${entrada.s3.secret-key}'
  compression: 'snappy'  


maxmind:
 max-age: 24
 license:
   paid: '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'


---

spring:
  profiles: controller 
  flyway:
    enabled: true
    
server:
 port: 8091

     
---

spring:
  profiles: worker 
  
server:
 port: 8090
 
management:
  endpoints:
    web:
      exposure:
        include: '*'

 