apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrada2
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: entrada2
  template:
    metadata: 
      labels:
        app: entrada2
        app.kubernetes.io/name: entrada2
    spec:
      serviceAccount: entrada2
      serviceAccountName: entrada2
      containers:
      - name: entrada2
        image: sidnlabs/entrada2:0.0.11
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
         - name: AWS_ACCESS_KEY_ID
           valueFrom:
             secretKeyRef:
               name: entrada2-secret
               key: s3.access-key
         - name: AWS_SECRET_ACCESS_KEY
           valueFrom:
             secretKeyRef:
               name: entrada2-secret
               key: s3.secret-access-key
         - name: AWS_REGION
           value: eu-west-1    
         - name: SPRING_RABBITMQ_USERNAME
           valueFrom:
             secretKeyRef:
               name: entrada2-secret
               key: rabbitmq.username
         - name: SPRING_RABBITMQ_PASSWORD
           valueFrom:
             secretKeyRef:
               name: entrada2-secret
               key: rabbitmq.password
         - name: ICEBERG_CATALOG_OAUTH2_CREDENTIAL
           valueFrom:
             secretKeyRef:
               name: entrada2-secret
               key: oauth2.credential
         - name: MANAGEMENT_INFLUX_TOKEN
           valueFrom:
             secretKeyRef:
               name: entrada2-secret
               key: influx.token
         - name: MAXMIND_LICENSE_PAID
           valueFrom:
             secretKeyRef:
               name: entrada2-secret
               key: maxmind.license   
        envFrom:
          - configMapRef:
              name: entrada2-config

