apiVersion: v1
kind: ServiceAccount
metadata:
  name: entrada2
  namespace: entrada2

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-and-secret-reader
  namespace: entrada2 
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-binding
  namespace: entrada2
subjects:
  - kind: ServiceAccount
    name: entrada2
    namespace: entrada2
roleRef:
  kind: Role
  name: config-and-secret-reader
  apiGroup: rbac.authorization.k8s.io


