apiVersion: v1
kind: Service
metadata:
  name: svc-entrada2
spec:
  type: ClusterIP
  selector:
    app: entrada2
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http

