server:
 port: 8091

spring:
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: '2GB'
      max-request-size: '2GB'

  datasource:
    url: 'jdbc:postgresql://localhost:5432/entrada2'
    username: ''
    password: ''

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: 'org.hibernate.dialect.PostgreSQLDialect'

