server:
 servlet:
   contextPath: '/api/v1'

entrada:
  parquet:
   file:
     # max Parquet filesize (mb)
     max-size: 256
  worker:
    # how long to sleep when no work (secs)
    sleep: 10
    # if worker time processing pcap > x min, it is marked as stalled
    stalled: 10
  schedule:
    # update reference data every x min
    updater: 60
    # check for stalled worker every x min
    liveness: 1
  security:
    token: '94591089610224297274859827590711'
  privacy:
    enabled: false
  directory:
    pcap: 'pcap'
    reference: 'reference'
  s3:
    access-key: '${AWS_ACCESS_KEY_ID}'
    secret-key: '${AWS_SECRET_ACCESS_KEY}'
    region: 'eu-west-1'
    endpoint:
    bucket: 'sidnlabs-iceberg-data'
  messaging:
    request-queue: 'entrada-s3-event'
    command-queue: 'entrada-command'
    leader-queue: 'entrada-leader'
  leader: true # leader setting for non k8s deployments
  metrics:
    enabled: true
    influxdb:
      org: SIDN
      bucket: entrada
      token: '${INFLUXDB_AUTH_TOKEN}'
      url: '${INFLUXDB_URL}'
      env: test

spring:
 main:
   allow-circular-references: true
 application: 
   name: 'entrada2'
 rabbitmq:
    enabled: true
    host: '${RABBITMQ_HOST}'
    password: '${RABBITMQ_PASSWORD}'
    username: '${RABBITMQ_USER}'
    request-queue: entrada-s3-events
    retry-attempts: 3
    backoff-interval: 1000
    backoff-multiplier: 2
    backoff-max-interval: 5000
    concurrent-consumers: 1
    max-concurrent-consumers: 1
 cloud:
 #   config:
 #     import-check:
 #       enabled: false
    bootstrap:
      enabled: false
    kubernetes:
      config:
        enabled: false
      enabled: false
      reload:
        enabled: false
      leader:
        config-map-name: entrada-leader
        role: master 
    aws:
      sqs:
        enabled: false
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
          maxmindClient:
            url: 'https://download.maxmind.com/app/geoip_download?suffix=tar.gz'
            dismiss404: false

#logging:
#  level:
#    root: DEBUG
   
#logging:
#  level:
#    nl.sidn.entrada2: DEBUG
 
iceberg:
  catalog:
    url: 
    token: secret_token_change_me_fast
  warehouse-dir: 'warehouse'
  compression: 'gzip'
  metadata:
    version:
      max: 100
  table:
    namespace: 'entrada2'
    name: 'dns'
    location: 's3://${entrada.s3.bucket}/entrada2'
    sorted: true #sort increases resource usage on servers
  parquet:
    dictionary-max-bytes: 10240
    page-limit: 20000
    bloomfilter: true
  connection:
    timeout: 5000
  

#########################
#        Resolvers      #
#########################

# max size of the "IP address to resolver" match cache
# keep cache because checking IP address is expensive
# but must make sure not to use a giant cache and get out-of-memory error
resolver:
  match:
    cache:
      size: 10000
  google:
    hostname: 'locations.publicdns.goog.'
    timeout: 15
  opendns:
    url: 'https://umbrella.cisco.com/why-umbrella/global-network-and-traffic'
    timeout: 15
  cloudflare:
    url:
      v4: 'https://www.cloudflare.com/ips-v4'
      v6: 'https://www.cloudflare.com/ips-v6'
      timeout: 15
     

  
#########################
#      MaxMind GeoIP    #
#########################
maxmind:
 max-age: 24
 license:
   free:
   paid:
 country:
   free: 'GeoLite2-Country'
   paid: 'GeoIP2-Country'
 asn:
   free: 'GeoLite2-ASN'
   paid: 'GeoIP2-ISP'
     

management:
  influx.metrics.export:
    enabled: false
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus'
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true    
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    heapdump:
      enabled: false
    logfile:
      enabled: false
       
       

