apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: entrada-worker-service
  name: entrada-worker-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: entrada-worker-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: entrada-worker-service
    spec:
      containers:
      - image: entrada-worker:0.0.1-SNAPSHOT
        name: entrada-worker-service
        resources: {}
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: entrada-worker-service
  name: entrada-worker-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8081
  selector:
    app: entrada-worker-service
  type: NodePort
status: {}
