apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: entrada2
  name: entrada2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: entrada2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: entrada2
    spec:
      containers:
      - image: sidnlabs/entrada-worker:0.0.1
        name: entrada2
        resources: {}

status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: entrada2
  name: entrada2
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8081
  selector:
    app: entrada2
  type: NodePort
status: {}
