catalog:
  db:
    host: 'localhost'
    name: 'iceberg'
    user: 'iceberg'
    password: 'iceberg'
  
  s3:
    bucket: 'testbucket1'
    warehouse_dir: 'warehouse'
    endpoint: 'http://localhost:9000'
    access_key: 'minio666'
    secret_key: 'minio666'
  security:
    token: 'secret_token_change_me_fast'
  
server:
 port: 8182

spring:
 application: 
   name: 'iceberg-catalog-server-service'
 cloud:
   kubernetes:
     reload:
       enabled: true
 
 
aws:
  region: eu-west-1
  endpoint: 'http://localhost:9000'
