server:
 port: 8090
 servlet:
   contextPath: '/api/v1'

spring:
 application: 
   name: 'entrada-worker'
 cloud:
   openfeign:
     client:
       config:
         default:
           connectTimeout: 5000
           readTimeout: 5000
           loggerLevel: basic
         workerClient:
           url: 'http://localhost:8080/api/v1'
           dismiss404: true

 
      
 management: 
   endpoints:
     web:
       base-path: '/api/v1/manager' 
 #      exposure:
 #        include: '*'

 
 
aws:
  accesskey: DrDd94eGYZBeFpukUsSW
  secretkey: tHKvt6ew3m0s0X0nYUsPGQtE5GFst7Sihxn8ZZJ7
  region: us-east-1
  endpoint: 'http://localhost:9000'
  bucket: testbucket1

  
#########################
#      MaxMind GeoIP    #
#########################
maxmind:
 max-age: 24
 license:
   free: ''
   paid: ''
 country:
   free: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&suffix=tar.gz&license_key='
   paid: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoIP2-Country&suffix=tar.gz&license_key='
 asn:
   free: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&suffix=tar.gz&license_key='
   paid: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoIP2-ISP&suffix=tar.gz&license_key='
     
