entrada:
  mode: 'controller'

server:
 port: 8091

spring:
  application:
    name: 'entrada-controller'
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: '2GB'
      max-request-size: '2GB'

  datasource:
    url: 'jdbc:postgresql://localhost:5432/entrada2'
    username: 'entrada2'
    password: 'entrada2'

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      
  autoconfigure:
    exclude: '' 


flyway:
   enabled: true

#aws.accesskey=minio666
#aws.secretkey=minio666
#aws.region=eu-west-1
#aws.endpoint=http://localhost:9000
#aws.bucket=testbucket1
#aws.directory=pcap
