package nl.sidn.entrada2.load;

//ENUM for fast access to the index of a record field, this saves an additional lookup to
//find index for field name.
public enum FieldEnum {
  dns_id,
  time,
  dns_qname,
  dns_domainname,
  ip_ttl,
  ip_version,
  prot,
  ip_src,
  prot_src_port,
  ip_dst,
  prot_dst_port,
  dns_aa,
  dns_tc,
  dns_rd,
  dns_ra,
  dns_ad,
  dns_cd,
  dns_ancount,
  dns_arcount,
  dns_nscount,
  dns_qdcount,
  dns_opcode,
  dns_rcode,
  dns_qtype,
  dns_qclass,
  ip_geo_country,
  ip_asn,
  ip_asn_org,
  edns_udp,
  edns_version,
  edns_do,
  edns_options,
  edns_ecs,
  edns_ecs_ip_asn,
  edns_ecs_ip_asn_org,
  edns_ecs_ip_geo_country,
  edns_ext_error,
  dns_labels,
  dns_proc_time,
  dns_pub_resolver,
  dns_req_len,
  dns_res_len,
  tcp_rtt,
  server,
  server_location,
  dns_rdata,
  dns_cname;
	
}
